#!/bin/bash

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_file_path=$1
server_ip=$2
username=$3
path_to_key_path=$4

# Disable strict host key checking for scp
export SSHPASS="yes"

# Transfer the file using scp
scp -o "StrictHostKeyChecking=no" -i "$path_ssh_key_path" "$path_file_path" "$username"@"$username@ip:~/"

# Check if the scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File transfer successful"
else
    echo "Error transferring file"
fi
