#!/usr/bin/env bash
#configures an uncomplicated firewall that blocks all incoming traffic
#for the tcp ports 22(ssh) 443(https ssl) and 80(http).

sudo apt install ufw
sudo ufw default deny incomming
sudo ufw default allow outgoing
sudo ufw allow 22tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
